# Generated by Django 2.2 on 2020-01-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankuser',
            name='change_times',
        ),
        migrations.RemoveField(
            model_name='bankuser',
            name='lastop_time',
        ),
        migrations.AddField(
            model_name='personalfinance',
            name='change_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='dept_id',
            field=models.IntegerField(default=0),
        ),
    ]
