# Generated by Django 2.2 on 2020-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20200128_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
