# Generated by Django 2.2 on 2020-01-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_dept_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfinance',
            name='submitter_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
